pipeline {

    agent {
        kubernetes {
          yamlFile 'Jenkins/container-builder.yaml'
        }
    }

    environment{
        SOURCE_REPOSITORY_URL = 'https://github.com/inganyoyo/hello-devops-gradle.git'
        MANIFEST_REPOSITORY_URL = 'https://github.com/inganyoyo/k8s-manifest.git'
        REPOSITORY_BRANCH = 'main'
        GIT_CREDENTIALS_ID = 'git-jenkins-token'
    }
    stages {

    stage('K8S Manifest Update') {
      steps {
        container('git-temp'){
            git credentialsId: "${GIT_CREDENTIALS_ID}",
                url: "https://github.com/inganyoyo/k8s-manifest.git",
                branch: "${REPOSITORY_BRANCH}"
            withCredentials([gitUsernamePassword(credentialsId: "${GIT_CREDENTIALS_ID}", passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {

                sh 'pwd'
                sh 'ls -lrt'
                sh 'cd hello-devops-gradle;'
                sh 'ls -lrt'
                sh 'cat hello-devops-gradle/deployment.yaml'
                sh 'sed -i "s/hello-devops-springboot:.*/hello-devops-springboot:${IMG_TAG}/g" hello-devops-gradle/deployment.yaml'
                sh 'cat hello-devops-gradle/deployment.yaml'

                sh "git config --global user.email inganyoyo@me.com"
                sh "git config --global user.name inganyoyo"
                sh "git config --global --add safe.directory /home/jenkins/agent/workspace/hello-devops-gradle-updatemanifest"
                sh 'git add hello-devops-gradle/deployment.yaml'
                sh "git commit -m 'fix:${IMG_TAG} image versioning---%{COMMIT_MSG}---'"
                sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/k8s-manifest.git HEAD:main"
            }
        }
      }
    }
//         }

//         stage('Update GIT') {
//             steps {
//                 container('git-temp') {
//
//                          git credentialsId: "${GIT_CREDENTIALS_ID}",
//                              url: "https://github.com/inganyoyo/k8s-manifest.git",
//                              branch: "${REPOSITORY_BRANCH}"
//
//                         withCredentials([usernamePassword(credentialsId: "${GIT_CREDENTIALS_ID}", passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
//                            sh "git config user.email inganyoyo@me.com"
//                            sh "git config user.name inganyoyo"
//                            sh "cat hello-devops-gradle/deployment.yaml"
//                            sh 'sed -i "s/hello-devops-springboot:.*/hello-devops-springboot:${BUILD_NUMBER}/g" hello-devops-gradle/deployment.yaml'
//                            sh 'cat hello-devops-gradle/deployment.yaml'
//                            sh "git add ."
//                            sh "git commit -m 'Done by Jenkins Job changemanifest: ${BUILD_NUMBER}'"
//                            sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/k8s-manifest.git HEAD:main"
//                        }
//
//                 }
//             }
//         }
    }
}


